WebUi/Controllers/AutoCompleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Application.UseCases.GetSomeData;
using Microsoft.AspNetCore.Mvc;

namespace WebUi.Controllers
{
    public class AutoCompleteController : Controller
    {
        private List<string> _states;

        public List<string> States
        {
            get
            {
                if (_states == null)
                    _states = GetStates();
                return _states;
            }

        }

        private List<string> GetStates()
        {
            List<string> states = new List<string>()
                { "Alabama", "Alaska", "American Samoa", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District Of Columbia", "Federated States Of Micronesia", "Florida", "Georgia", "Guam", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Marshall Islands", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Northern Mariana Islands", "Ohio", "Oklahoma", "Oregon", "Palau", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virgin Islands", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" };

            return states;
        }



        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        // [ValidateAntiForgeryToken]
        public string GetJQueryStates()
        {
                return "Alabama,Alaska,American Samoa,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District Of Columbia,Federated States Of Micronesia,Florida,Georgia,Guam,Hawaii,Idaho,Illinois,Indiana,Iowa,Kansas,Kentucky,Louisiana,Maine,Marshall Islands,Maryland,Massachusetts,Michigan,Minnesota,Mississippi,Missouri,Montana,Nebraska,Nevada,New Hampshire,New Jersey,New Mexico,New York,North Carolina,North Dakota,Northern Mariana Islands,Ohio,Oklahoma,Oregon,Palau,Pennsylvania,Puerto Rico,Rhode Island,South Carolina,South Dakota,Tennessee,Texas,Utah,Vermont,Virgin Islands,Virginia,Washington,West Virginia,Wisconsin,Wyoming";

        }

        //[HttpGet]
        //// [ValidateAntiForgeryToken]
        //public string JQueryAutoComplete(string searchValue)
        //{

        //    StringBuilder sb = new StringBuilder();
        //    sb.Append("<select id=\"autoCompleteSelect\" size=\"5\">");

        //    foreach (string state in States)
        //    {
        //        if (state.IndexOf(searchValue, 0, StringComparison.CurrentCultureIgnoreCase) != -1)
        //            sb.Append("<option value=\"" + state + "\">" + state + "</option>");
        //    }

        //    sb.Append("</select>");
        //    return sb.ToString();
        //}


        [HttpGet]
       // [ValidateAntiForgeryToken]
        public string MvcAutoComplete(string searchValue)
        {

            StringBuilder sb = new StringBuilder();
            sb.Append("<select id='autoCompleteSelect' size='5'>");

            foreach (string state in States)
            {
                if (state.IndexOf(searchValue, 0, StringComparison.CurrentCultureIgnoreCase) != -1)
                    sb.Append("<option>" + state + "</option>");
            }

            sb.Append("</select>");
            return sb.ToString();



            //StringBuilder sb = new StringBuilder();
            //sb.Append("<select id=\"autoCompleteSelect\" size=\"5\">");

            //foreach (string state in States)
            //{
            //    if (state.IndexOf(searchValue, 0, StringComparison.CurrentCultureIgnoreCase) != -1)
            //        sb.Append("<option value=\"" + state + "\">" + state + "</option>");
            //}

            //sb.Append("</select>");
            //return sb.ToString();

            //Dictionary<string, string> dataDictionary = new Dictionary<string, string>();
            //dataDictionary.Add("jQuery Validation of Email, Number, Checkbox and More", "http://www.yogihosting.com/using-jquery-to-validate-a-form/");
            //dataDictionary.Add("jQuery Uncheck Checkbox Tutorial", "http://www.yogihosting.com/check-uncheck-all-checkbox-using-jquery/");
            //dataDictionary.Add("Free WordPress Slider Built In jQuery", "http://www.yogihosting.com/wordpress-image-slider-effect-with-meta-slider/");
            //dataDictionary.Add("Creating jQuery Expand Collapse Panels In HTML", "http://www.yogihosting.com/creating-expandable-collapsible-panels-in-jquery/");
            //dataDictionary.Add("jQuery AJAX Events Complete Guide for Beginners and Experts", "http://www.yogihosting.com/jquery-ajax-events/");
            //dataDictionary.Add("How to Create a Web Scraper in ASP.NET MVC and jQuery", "http://www.yogihosting.com/web-scraper/");
            //dataDictionary.Add("CRUD Operations in Entity Framework and ASP.NET MVC", "http://www.yogihosting.com/crud-operations-entity-framework/");
            //dataDictionary.Add("Implementing TheMovieDB (TMDB) API in ASP.NET MVC", "http://www.yogihosting.com/implement-themoviedb-api/");
            //dataDictionary.Add("ASP.NET MVC Data Annotation – Server Side Validation of Controls", "http://www.yogihosting.com/server-side-validation-asp-net-mvc/");
            //dataDictionary.Add("How to use CKEditor in ASP.NET MVC", "http://www.yogihosting.com/ckeditor-tutorial-asp-net-mvc/");

            //StringBuilder sb = new StringBuilder();
            //sb.Append("<select id=\"autoCompleteSelect\" size=\"5\">");

            //foreach (KeyValuePair<string, string> entry in dataDictionary)
            //{
            //    if (entry.Key.IndexOf(searchValue, 0, StringComparison.CurrentCultureIgnoreCase) != -1)
            //        sb.Append("<option value=\"" + entry.Value + "\">" + entry.Key + "</option>");
            //}

            //sb.Append("</select>");
            //return sb.ToString();
        }

       private List<string> GetAutocompleteStates(string value)
       {
           var states = States.Where(s => s.Contains(value)).ToList();
            return states;

       }



    }
}

WebUi/Views/AutoComplete/Index.cshtml
<style>



    h3 {
        font-size: 23px;
        border-bottom: solid 3px #CCC;
        padding-bottom: 10px;
    }

    h3 a {
        color: #00e8ff;
        text-decoration: none;
    }

    h3 a:hover, h2 a:hover {
        text-decoration: underline;
    }



    .container #content {
        padding: 10px;
    }

    #reset {
        padding: 5px 10px;
        background: #4CAF50;
        border: none;
        color: #FFF;
        cursor: pointer;
    }

        #reset:hover {
            color: #4CAF50;
            background: #FFF;
        }

    #viewContent #searchInput, #viewContent #autoCompleteSelect {
        width: 430px;
    }

    #viewContent #searchInput {
        padding: 5px 0;
    }

    #viewContent #autoCompleteSelect option:hover {
        background-color: #d8fff7;
        cursor: pointer;
    }

</style>



<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
@*<script src="/mvc/Content/JS/jquery-2.2.4.js"></script>*@

<p></p>
<p>
    This part demonstrates performing the generation of the auto-complete values on the server.<br />
    We do it in two different ways: <br />
    1. We perform the autocomplete on the server using AJAX calls without promises<br />
    2. We use JQuery UI's autocomplete function after we pre-populated the list in the UI using an AJAX and we also make use of promises.
</p>

        <div id="viewContent">
            <input type="text" id="searchInput" placeholder="Enter a state" />
            <div id="autoCompleteDiv"></div>
        </div>

<p></p>
<p>This part pre-populates the full list using an ajax call and using JQuery's autocomplete features.</p>

<div class="ui-widget">
    <input id="myStates" placeholder="Enter a state" />
</div>


<script>

    var states;
    $(document).ready(function() {


        // This pre-populates a variable that will contain all possible auto-complete value.
        $.ajax({
                type: "GET",
                url: '@Url.Action("GetJQueryStates", "AutoComplete")',
                dataType: "html"
            })
            .done(function(result) {
                states = result.split(",");

                $('#myStates').autocomplete({
                    source: states
                });
            })
            .fail(function(xhr, status, error) {
                alert(xhr + " " + status + " " + error);
            });
    


        // The code below handles the MVC autocomplete.
        $("#searchInput").keyup(function (event) {
            if (event.which == 40) /*Arrow Down*/
            {
                $("#autoCompleteSelect").val($("#autoCompleteSelect option:first").val());
                $("#autoCompleteSelect").focus();
                $(this).val($("#autoCompleteSelect :selected").text());
            }
            else {
                if ($(this).val().length > 2) {
                    FillAutoComplete($(this).val());
                }
                else
                    $("#autoCompleteDiv").hide();
            }
        });



        //key up event

        function FillAutoComplete(value) {
            $.ajax({
                type: "GET",
                url: '@Url.Action("MvcAutoComplete", "AutoComplete")' + '?searchValue=' + value,
                dataType: "html",
                success: function (result, status, xhr) {
                    $("#autoCompleteDiv").html(result.replace(/\$\$/g, '"'));
                    $("#autoCompleteDiv").show();
                },
                error: function (xhr, status, error) {
                    alert(xhr + " " + status + " " + error);
                }
            });
            return false;
        }

        $("#viewContent").on("change", "#autoCompleteSelect", function () {
            $("#searchInput").val($("#autoCompleteSelect :selected").text());
        });

        $("#viewContent").on("click", "#autoCompleteSelect", function () {
            $("#autoCompleteDiv").hide();
        });

    });
</script>